import CardComponent from "../components/CardComponent";
import AreaChart from '../components/ areachart';
import BarChart from '../components/BarChart';
import DataTableComponent from "../components/DataTableComponent";
import Head from "next/head";

import Navbar from "../components/navbar";

export default function Home() {
    return (
        <div>
            <div className="container">
                <div className="cards d-flex gap-3 mt-5 p-5 flex-column flex-lg-row">
                    <CardComponent bgColor='bg-primary' text='Primary Card'/>
                    <CardComponent bgColor='bg-warning' text='Warning Card'/>
                    <CardComponent bgColor='bg-success' text='Success Card'/>
                    <CardComponent bgColor='bg-danger' text='Danger Card'/>
                </div>
                <div className="row">
                    <div className="col-xl-6">
                        <AreaChart/>
                    </div>
                    <div className="col-xl-6">
                        <BarChart/>
                    </div>
                </div>
            </div>
            <DataTableComponent/>
        </div>

    )
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
          rel="stylesheet"
        />
        {/* <script
          src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
          crossorigin="anonymous"
        ></script> */}
      </Head>

      <Navbar />
    </div>
  );
}
