import Head from "next/head";

import Navbar from "../components/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
          rel="stylesheet"
        />
        {/* <script
          src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
          crossorigin="anonymous"
        ></script> */}
      </Head>

      <Navbar />
    </div>
  );
}
